# Generated by Django 5.1.4 on 2025-01-09 12:33

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInterval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=True)),
                ('activity_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tasks_time', models.JSONField(default=dict)),
                ('screenshots', models.JSONField(default=list)),
                ('headshots', models.JSONField(default=list)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed'), ('SUSPICIOUS', 'Suspicious Activity')], default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'activity_intervals',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('active_time', models.PositiveIntegerField(default=0)),
                ('idle_time', models.PositiveIntegerField(default=0)),
                ('average_activity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('first_activity', models.TimeField(null=True)),
                ('last_activity', models.TimeField(null=True)),
                ('projects_summary', models.JSONField(default=dict)),
                ('tasks_summary', models.JSONField(default=dict)),
                ('hourly_breakdown', models.JSONField(default=dict)),
                ('week_number', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'activity_stats',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('budget_type', models.CharField(choices=[('FIXED', 'Fixed'), ('HOURLY', 'Hourly')], default='HOURLY', max_length=10)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('settings', models.JSONField(default=dict)),
                ('is_billable', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_billable', models.BooleanField(default=True)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due_date', 'priority', '-created_at'],
            },
        ),
    ]
