# Generated by Django 5.1.4 on 2025-08-20 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_time', models.JSONField(default=dict)),
                ('active_app', models.JSONField(default=dict)),
                ('screenshots', models.JSONField(default=list)),
                ('headshots', models.JSONField(default=list)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='users.employee')),
            ],
            options={
                'db_table': 'tracking_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'updated_at'], name='tracking_se_employe_fe5612_idx')],
            },
        ),
    ]
