# Generated by Django 5.1.4 on 2025-08-21 11:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_trackingsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingsession',
            old_name='active_app',
            new_name='active_apps',
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='activity_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='is_online',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ActiveAppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('minutes', models.FloatField(default=0.0)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='stats.trackingsession')),
            ],
            options={
                'db_table': 'active_app_usage',
                'indexes': [models.Index(fields=['app_name', 'timestamp'], name='active_app__app_nam_79c5f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeadshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headshot_logs', to='stats.trackingsession')),
            ],
            options={
                'db_table': 'headshot_logs',
                'indexes': [models.Index(fields=['timestamp'], name='headshot_lo_timesta_ec7de1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreenshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('window_title', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_logs', to='stats.trackingsession')),
            ],
            options={
                'db_table': 'screenshot_logs',
                'indexes': [models.Index(fields=['timestamp'], name='screenshot__timesta_5202b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('project_id', models.UUIDField()),
                ('minutes', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='stats.trackingsession')),
            ],
            options={
                'db_table': 'task_usage',
                'indexes': [models.Index(fields=['task_id', 'timestamp'], name='task_usage_task_id_190551_idx')],
            },
        ),
    ]
