# Generated by Django 5.1.4 on 2025-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_rename_active_app_trackingsession_active_apps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeappusage',
            name='chunk_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeappusage',
            name='seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='chunk_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='effective_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='overtime_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='recorded_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='remaining_task_time_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='total_task_time_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskusage',
            name='total_worked_time_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='active_by_app_sec',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='active_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='app_session_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='app_session_duration_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='app_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='effective_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='idle_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='overtime_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='recorded_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
